---
version: "3.7"
services:
  mf-db:
    image: mysql:5.7
    container_name: mf-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'mf'
      MYSQL_USER: 'mf'
      MYSQL_PASSWORD: 'mf'
      MYSQL_ROOT_PASSWORD: 'mf'
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "database:/var/lib/mysql"
    networks:
      - mf
    labels:
      - traefik.enable=false

volumes:
  database:

networks:
  mf:
    external: True
