---

name: Development

on:
  push:
    branches:
      - master

jobs:
  deliver:
    runs-on: 
      - self-hosted
      - development
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Setup dev dependencies
        run: docker compose up --build -d
